default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: conta_bancaria_development

test:
  <<: *default
  database: conta_bancaria_test

production:
  <<: *default
  database: conta_bancaria_production
  username: conta_bancaria
  password: <%= ENV['CONTA_BANCARIA_DATABASE_PASSWORD'] %>
